# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BorrowMyAngel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  pod 'SendBirdSDK'

  # Pods for BorrowMyAngel

  target 'BorrowMyAngelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
